addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.5.0")
addSbtPlugin("ch.epfl.scala"        % "sbt-scalafix"                  % "0.10.4")
addSbtPlugin("com.github.sbt"       % "sbt-pgp"                       % "2.2.1")
addSbtPlugin("com.github.sbt"       % "sbt-dynver"                    % "5.0.1")
addSbtPlugin("org.xerial.sbt"       % "sbt-sonatype"                  % "3.9.21")
addSbtPlugin("com.github.sbt"       % "sbt-git"                       % "2.0.1")
